create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null,
    password_hash varchar(255) not null
);

alter table if exists teams
    add column if not exists owner_id bigint;

alter table if exists players
    add column if not exists owner_id bigint;

alter table if exists matches
    add column if not exists owner_id bigint;
